field: 2816a112-88bc-41d8-a9cf-ddb13c62c52a # Hero
fieldLayouts:
  0d6ec4c6-0daf-4417-83d9-c6f38691bd81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bb45d14f-3863-4f58-9763-ef62548e58fd # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 813c5884-a28a-41ea-ac85-e22c1caeb6e2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a57f88c4-6b1f-447b-afc9-c5f56310b915 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dbf4c34-5ccc-4c52-84f3-dc55e89f2729
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee00a92d-d445-49c8-aef2-777434617a63 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4568f526-25ea-45ff-aab4-dcc0c0fcbad9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9985adfc-d249-427d-aa15-64202fc66a7e
        userCondition: null
fields:
  a57f88c4-6b1f-447b-afc9-c5f56310b915: # Heading
    columnSuffix: ayzlgidr
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bb45d14f-3863-4f58-9763-ef62548e58fd: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:5def0e7b-ecaf-4850-9768-997d8e99c413' # Public
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5def0e7b-ecaf-4850-9768-997d8e99c413' # Public
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ee00a92d-d445-49c8-aef2-777434617a63: # Subheading
    columnSuffix: chocsewo
    contentColumnType: text
    fieldGroup: null
    handle: subheading
    instructions: null
    name: Subheading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: hero
name: Hero
sortOrder: 1
