field: 93cfdf1d-91e2-4f8c-ba8a-8fddeb91f819 # Preaching
fieldLayouts:
  afbf7fff-2fb8-420b-bc61-806c68df950a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6075c734-f800-4eb5-af75-188865d82254 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89436cf1-2167-4419-be50-e4e3af6ef235
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f221e7e1-fa99-4779-baf7-686948c07867 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e5ba100-2e03-41c1-88b3-a58518f3701a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3dd5dbf-d57e-491c-a156-d5ecdf254d98 # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9223b6bb-b20e-411a-aac3-2c8cb2605af6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c52af6c0-0f60-49eb-91b9-4ee6e22b0cf3
        userCondition: null
fields:
  6075c734-f800-4eb5-af75-188865d82254: # Heading
    columnSuffix: btujsuzf
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e3dd5dbf-d57e-491c-a156-d5ecdf254d98: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: null
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:5def0e7b-ecaf-4850-9768-997d8e99c413' # Public
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5def0e7b-ecaf-4850-9768-997d8e99c413' # Public
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f221e7e1-fa99-4779-baf7-686948c07867: # Subheading
    columnSuffix: ecfcpenp
    contentColumnType: text
    fieldGroup: null
    handle: subheading
    instructions: null
    name: Subheading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: preaching
name: Preaching
sortOrder: 1
