fieldLayouts:
  b231dfa9-a5a7-429f-ae7e-f68f2481c17f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7da6c89e-ba4d-43d6-8f6a-422f0e0374f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f76a43a7-a1a0-40f9-b82c-0803a9257b79 # Heading and Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5e2348d-02c3-45b7-a3e0-156199242e6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4706fd84-7418-404a-98cc-edd315aafe63 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4f9a332-aa4f-4209-89ee-e7bee022ee57
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b78f56b-ac40-4c34-8d37-2645c7db3424 # Card and Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e046ed0-6cf8-4fd6-b083-81f30284dfff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d57703e-7d08-4887-b294-1fd3701e52ec # Statement
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b94a369a-2b8c-468f-9702-da0fda00f732
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1fdce953-f995-4972-872d-727df763d639 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7251bae-01b1-44ca-a0e3-8581d2bf11fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a69ad962-1e03-409e-b6fa-97b5d6a4dbfe # Card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bf1fb2b-7a79-471a-b107-3253477d46e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d4b2cd0-1219-493d-a02d-16e0fb36f0cc
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 6ba24b65-1e36-488f-ab3a-bbb993f8e406 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
