fieldLayouts:
  b231dfa9-a5a7-429f-ae7e-f68f2481c17f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7da6c89e-ba4d-43d6-8f6a-422f0e0374f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1fdce953-f995-4972-872d-727df763d639 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7251bae-01b1-44ca-a0e3-8581d2bf11fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2a5a59a1-1925-46a0-b83f-99fe76ae603b # Text Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa648684-f993-49ed-8bf2-a475c3a090d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4706fd84-7418-404a-98cc-edd315aafe63 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4f9a332-aa4f-4209-89ee-e7bee022ee57
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b78f56b-ac40-4c34-8d37-2645c7db3424 # Card and Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e046ed0-6cf8-4fd6-b083-81f30284dfff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d4b2cd0-1219-493d-a02d-16e0fb36f0cc
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 6ba24b65-1e36-488f-ab3a-bbb993f8e406 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
