fieldLayouts:
  b231dfa9-a5a7-429f-ae7e-f68f2481c17f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7da6c89e-ba4d-43d6-8f6a-422f0e0374f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d4b2cd0-1219-493d-a02d-16e0fb36f0cc
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 6ba24b65-1e36-488f-ab3a-bbb993f8e406 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
