fieldLayouts:
  98c8d059-9022-43ab-b4f5-e104031f0ad8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 95dc6caf-a045-4f32-9604-5ce4944c6ed2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b0f09634-5678-45e3-bf4f-5a9678e10c3b # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c80b3daf-67dd-4f85-8e0e-25f8edfe3f1a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 176a94e5-7f6d-456a-bf5e-d0e3fb463a53 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c34e7beb-3520-44d1-9f3f-9e6988755236
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 487ca65d-4c50-4516-aad8-b6bac25368a4 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f681204e-ba28-4c0f-a6b1-3fdcb1ece2f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec01bd9a-d1fa-450c-8fb7-8e17cffa861f # Rich Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e1b5e04-bd18-45bf-a6fc-6bb36ffaa821
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05e0bc2a-6489-4ab0-ba38-7637ba553d8d
        userCondition: null
handle: event
hasTitleField: true
name: Event
section: 73d111c9-de63-4afa-b708-9a3ce35bc668 # Events
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
