fieldLayouts:
  95863f18-8768-46ad-93ce-679681bfe6d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5260846c-a207-4bb5-9549-08038d404b1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1fdce953-f995-4972-872d-727df763d639 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3be3626-db3a-4322-832f-584a69984443
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 176a94e5-7f6d-456a-bf5e-d0e3fb463a53 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97b05d18-fc7c-499a-a327-c885edc2d98f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1e03e5c-99ba-42bc-98a4-26808ccc4745 # Times and Locations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a7bcd8a-4a70-4221-b29f-38a4739c34e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f17920de-fd30-4278-80c9-758a45945864 # Image and Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a154515c-e3de-449c-9dcd-84c8281e2649
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e2084655-36e3-4221-84ec-99cb90eb395a # FAQ
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6a4ca66-795a-44f7-a00a-87fbc1b188a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ca12cc10-d547-46ed-b942-b06274423157
        userCondition: null
handle: visitUs
hasTitleField: false
name: 'Visit Us'
section: 24b7c0fa-cf4a-481e-8841-cf8f89ec4ac3 # Visit Us
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
