fieldLayouts:
  d5341e6d-e7d4-425d-817c-234b7ce248ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5d943efc-ecfa-43fc-98fb-ec55af06c559
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 69c85163-d743-4c98-9417-9beba2dc512a
        userCondition: null
fs: ministries
handle: ministries
name: Ministries
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
