columnSuffix: null
contentColumnType: string
fieldGroup: fe4865ba-4f7c-4d0b-b40d-d9f765030adc # Common
handle: faq
instructions: null
name: FAQ
searchable: false
settings:
  contentTable: '{{%matrixcontent_faq}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
