defaultPlacement: end
enableVersioning: true
handle: contactForm
name: 'Contact Form'
propagationMethod: all
siteSettings:
  92c2ec1a-379c-4edf-83c4-d3a564b9010a: # SOF
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: contact-form
type: single
