defaultPlacement: end
enableVersioning: true
handle: visitUs
name: 'Visit Us'
propagationMethod: all
siteSettings:
  92c2ec1a-379c-4edf-83c4-d3a564b9010a: # SOF
    enabledByDefault: true
    hasUrls: true
    template: visit-us.twig
    uriFormat: visit-us
type: single
